import { yekan } from "@/core/utils/Font";
import TanstackQueryProvider from "@/core/providers/TanstackQueryProvider";
import "./globals.css";
import Header from "@/components/templates/Header";
import Footer from "@/components/templates/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className={yekan.className}>
        <TanstackQueryProvider>
          <Header />
          <main className="min-h-svh	">{children}</main>
          <Footer />
        </TanstackQueryProvider>
      </body>
    </html>
  );
}
