import { yekan } from "@/core/utils/Font";
import TanstackQueryProvider from "@/components/partials/providers/TanstackQueryProvider";
import "./globals.css";
import Header from "@/components/templates/header";
import Footer from "@/components/templates/footer";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl" className={`${yekan.className}`}>
      <body >
        <TanstackQueryProvider>
          <Header />
          <main className="min-h-svh	">{children}</main>
          <Footer />
        </TanstackQueryProvider>
        <Toaster/>
      </body>
    </html>
  );
}
